"""Add A/B testing columns to usage_analytics

Revision ID: 9aaa849bc8ca
Revises: 
Create Date: 2025-10-31 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aaa849bc8ca' # <-- MAKE SURE THIS MATCHES YOUR FILENAME
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- THE MANUAL FIX: PART 1 ---
    # We must first create the new ENUM type in the database.
    op.execute("CREATE TYPE useraction AS ENUM ('accepted', 'rejected', 'modified')")
    
    op.add_column('usage_analytics', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('usage_analytics', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('usage_analytics', sa.Column('experiment_group', sa.String(length=50), nullable=True))
    op.add_column('usage_analytics', sa.Column('enhancement_strategy', sa.String(length=100), nullable=True))
    # Note the change on the next line: we specify server_default=None and tell Postgres the type name now exists.
    op.add_column('usage_analytics', sa.Column('user_action', sa.Enum('accepted', 'rejected', 'modified', name='useraction', create_type=False), server_default=None, nullable=True))
    op.create_index(op.f('ix_usage_analytics_user_id'), 'usage_analytics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_analytics_user_id'), table_name='usage_analytics')
    op.drop_column('usage_analytics', 'user_action')
    op.drop_column('usage_analytics', 'enhancement_strategy')
    op.drop_column('usage_analytics', 'experiment_group')
    op.drop_column('usage_analytics', 'session_id')
    op.drop_column('usage_analytics', 'user_id')
    
    # --- THE MANUAL FIX: PART 2 ---
    # We must also drop the ENUM type if we roll back this migration.
    op.execute("DROP TYPE useraction")
    
    # ### end Alembic commands ###