"""Add A/B testing columns to usage_analytics

Revision ID: 9aaa849bc8ca
Revises: 
Create Date: 2025-10-31 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aaa849bc8ca' # <-- MAKE SURE THIS MATCHES YOUR FILENAME
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- CREATE TABLES IF THEY DON'T EXIST ---
    # First, create the prompt_cache table if it doesn't exist
    op.execute("""
        CREATE TABLE IF NOT EXISTS prompt_cache (
            id SERIAL PRIMARY KEY,
            original_prompt TEXT NOT NULL UNIQUE,
            enhanced_prompt TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    
    # Create index on original_prompt if it doesn't exist
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_prompt_cache_original_prompt ON prompt_cache(original_prompt)
    """)
    
    # Create the usage_analytics table if it doesn't exist (with base columns only)
    op.execute("""
        CREATE TABLE IF NOT EXISTS usage_analytics (
            id SERIAL PRIMARY KEY,
            prompt_id INTEGER NOT NULL REFERENCES prompt_cache(id),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    
    # Create index on prompt_id if it doesn't exist
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_usage_analytics_prompt_id ON usage_analytics(prompt_id)
    """)
    
    # --- THE MANUAL FIX: PART 1 ---
    # We must first create the new ENUM type in the database (if it doesn't exist).
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE useraction AS ENUM ('accepted', 'rejected', 'modified');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Now add the A/B testing columns (only if they don't exist)
    # Check and add user_id
    op.execute("""
        DO $$ BEGIN
            ALTER TABLE usage_analytics ADD COLUMN user_id UUID;
        EXCEPTION
            WHEN duplicate_column THEN null;
        END $$;
    """)
    
    # Check and add session_id
    op.execute("""
        DO $$ BEGIN
            ALTER TABLE usage_analytics ADD COLUMN session_id UUID;
        EXCEPTION
            WHEN duplicate_column THEN null;
        END $$;
    """)
    
    # Check and add experiment_group
    op.execute("""
        DO $$ BEGIN
            ALTER TABLE usage_analytics ADD COLUMN experiment_group VARCHAR(50);
        EXCEPTION
            WHEN duplicate_column THEN null;
        END $$;
    """)
    
    # Check and add enhancement_strategy
    op.execute("""
        DO $$ BEGIN
            ALTER TABLE usage_analytics ADD COLUMN enhancement_strategy VARCHAR(100);
        EXCEPTION
            WHEN duplicate_column THEN null;
        END $$;
    """)
    
    # Check and add user_action
    op.execute("""
        DO $$ BEGIN
            ALTER TABLE usage_analytics ADD COLUMN user_action useraction;
        EXCEPTION
            WHEN duplicate_column THEN null;
        END $$;
    """)
    
    # Create index on user_id if it doesn't exist
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_usage_analytics_user_id ON usage_analytics(user_id)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_analytics_user_id'), table_name='usage_analytics')
    op.drop_column('usage_analytics', 'user_action')
    op.drop_column('usage_analytics', 'enhancement_strategy')
    op.drop_column('usage_analytics', 'experiment_group')
    op.drop_column('usage_analytics', 'session_id')
    op.drop_column('usage_analytics', 'user_id')
    
    # --- THE MANUAL FIX: PART 2 ---
    # We must also drop the ENUM type if we roll back this migration.
    op.execute("DROP TYPE useraction")
    
    # ### end Alembic commands ###